export const CATEGORIES = [
  { slug: "large-cap", label: "Large Cap" },
  { slug: "mid-cap", label: "Mid Cap" },
  { slug: "small-cap", label: "Small Cap" },
  { slug: "flexi-cap", label: "Flexi Cap" },
  { slug: "elss", label: "ELSS" },
  { slug: "focused", label: "Focused" },
  { slug: "value", label : "Value"},
  { slug: "contra", label : "Contra"},
  { slug: "multi-cap", label: "Multi Cap"},
  { slug: "large-mid-cap", label: "Large and Mid Cap"},
  { slug: "healthcare", label: "Healthcare"},
  { slug: "banking-financial-services", label: "Banking & Financial Services"},
  { slug: "technology", label: "Technology"},
  { slug: "quant", label: "Quant"},
  { slug: "infrastructure", label: "Infrastructure"},
  { slug: "business-cycle", label: "Business Cycle"},
  { slug: "esg", label: "ESG"},
  { slug: "consumption", label: "Consumption"}
];
